### ISSUE TITLE
[FEATURE REQUEST] Readable Code

### ISSUE THREAD

**Issue by hoffination** [crashmoney/obsidian-typewriter#44]
## Describe your feature request
I love how this theme is sized and the general feel. It makes a delightful and legible experience that resonates with me, however, I'd like to see code sizes shrink slightly.

## Proposed Solution
I add this CSS manually to my machine and perhaps it might be helpful for others seeking to do the same:

```css
/* Set code to a smaller size*/
.cm-s-obsidian .HyperMD-codeblock {
    font-size: var(--font-smaller);
}

/* Set PDF code print size smaller */
@media print {
    pre > code {
        font-size: 10pt !important;
    }
}
```

## Additional Context
Here is a screenshot of it working in conjunction with the [Code Styler](https://github.com/mayurankv/Obsidian-Code-Styler) plugin:

![Screenshot 2024-04-30 at 3 42 53 PM](https://github.com/crashmoney/obsidian-typewriter/assets/2348974/28ec5b0d-ae9e-4dc1-baa4-d92087779898)
